name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/upload-artifact@v3
      name: "Upload artifacts"
      with:
        name: latest
        path: target/release/rust_api
        retention-days: 7

