name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/

      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v3
        name: "Upload artifacts"
        with:
          name: latest
          path: target/release/rust_api
          retention-days: 7

